/**
 * robots.txt, generated by Next's file convention.
 *
 * There was none, so crawlers got a 404 and had to guess. The site is
 * set to `index: true` in the root layout, so the intent has always been
 * to be indexed; this states it, and points at the sitemap.
 *
 * `/api/` is disallowed because nothing under it is a page. It is one
 * POST-only route that answers a form, and there is nothing there for a
 * crawler to read or index.
 */
import { brand } from '@/config/site';

export default function robots() {
    return {
        rules: {
            userAgent: '*',
            allow: '/',
            disallow: '/api/',
        },
        sitemap: `https://${brand.domain}/sitemap.xml`,
    };
}
