/**
 * sitemap.xml, generated by Next's file convention.
 *
 * Every indexable page, listed once. The route list is written by hand
 * rather than discovered, because the only alternative is walking the
 * app directory at build time and that would happily include things
 * that should never be in a sitemap: the OG image, the icon, and the
 * API route are all "routes" but none is a page.
 *
 * `priority` is relative within this site only, not a claim about the
 * wider web. The two pages that sell something rank above the three
 * legal pages, which exist to be findable rather than to be found.
 */
import { brand } from '@/config/site';
import { VERTICALS } from '@/content/verticals';
import fs from 'node:fs';
import path from 'node:path';

const PAGES = [
    { path: '', priority: 1.0, changeFrequency: 'monthly' },
    { path: '/cloud', priority: 0.9, changeFrequency: 'monthly' },
    /* The three service pages. High priority because they are the only
       pages on this site written to be found cold from a search rather
       than reached from the home page. */
    { path: '/services/websites', priority: 0.9, changeFrequency: 'monthly' },
    { path: '/services/seo', priority: 0.8, changeFrequency: 'monthly' },
    { path: '/services/content-and-social', priority: 0.8, changeFrequency: 'monthly' },
    { path: '/cloud/onboarding', priority: 0.6, changeFrequency: 'yearly' },
    { path: '/privacy', priority: 0.3, changeFrequency: 'yearly' },
    { path: '/terms', priority: 0.3, changeFrequency: 'yearly' },
    { path: '/credits', priority: 0.3, changeFrequency: 'yearly' },
];

/* One entry per business vertical that actually has a written landing
   page. VERTICALS lists all 24 slugs the route CAN serve, but only the
   ones with a content/verticals/<slug>.js file resolve to a real page;
   the rest 404 (see app/for/[slug]/page.js). Listing a 404 in the
   sitemap teaches Google that the sitemap is unreliable, so this checks
   the file exists rather than assuming the whole list is live. */
function liveVerticalPaths() {
    return VERTICALS
        .filter((v) => fs.existsSync(path.join(process.cwd(), 'content', 'verticals', `${v.slug}.js`)))
        .map((v) => ({ path: `/for/${v.slug}`, priority: 0.7, changeFrequency: 'monthly' }));
}

export default function sitemap() {
    /* One timestamp for the whole build. Per-page dates would need a real
       source (git mtime, a CMS); inventing them per request would tell
       crawlers the pages change daily when they do not. */
    const lastModified = new Date();

    return [...PAGES, ...liveVerticalPaths()].map(({ path: p, priority, changeFrequency }) => ({
        url: `https://${brand.domain}${p}`,
        lastModified,
        changeFrequency,
        priority,
    }));
}
