/**
 * sitemap.xml, generated by Next's file convention.
 *
 * Every indexable page, listed once. The route list is written by hand
 * rather than discovered, because the only alternative is walking the
 * app directory at build time and that would happily include things
 * that should never be in a sitemap: the OG image, the icon, and the
 * API route are all "routes" but none is a page.
 *
 * `priority` is relative within this site only, not a claim about the
 * wider web. The two pages that sell something rank above the three
 * legal pages, which exist to be findable rather than to be found.
 */
import { brand } from '@/config/site';

const PAGES = [
    { path: '', priority: 1.0, changeFrequency: 'monthly' },
    { path: '/cloud', priority: 0.9, changeFrequency: 'monthly' },
    { path: '/cloud/onboarding', priority: 0.6, changeFrequency: 'yearly' },
    { path: '/privacy', priority: 0.3, changeFrequency: 'yearly' },
    { path: '/terms', priority: 0.3, changeFrequency: 'yearly' },
    { path: '/credits', priority: 0.3, changeFrequency: 'yearly' },
];

export default function sitemap() {
    /* One timestamp for the whole build. Per-page dates would need a real
       source (git mtime, a CMS); inventing them per request would tell
       crawlers the pages change daily when they do not. */
    const lastModified = new Date();

    return PAGES.map(({ path, priority, changeFrequency }) => ({
        url: `https://${brand.domain}${path}`,
        lastModified,
        changeFrequency,
        priority,
    }));
}
